apiVersion: v1
kind: Service
metadata:
  name: netcat
  labels:
    run: netcat
spec:
  type: NodePort
  # Optional - make the service headless by uncommenting the next line
  # clusterIp: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    run: netcat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcat
  labels:
    name: netcat
    app: netcat
    run: netcat
    version: 0.1.0
spec:
  selector:
    matchLabels:
      run: netcat
  replicas: 1
  template:
    metadata:
      labels:
        run: netcat
        app: netcat
    spec:
      containers:
      - name: netcat
        image: crccheck/hello-world
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000